[phases.setup]
nixPkgs = [
  'php83',
  'php83Extensions.mysqli',
  'php83Extensions.pdo',
  'php83Extensions.pdo_mysql',
  'php83Extensions.gd',
  'php83Extensions.mbstring',
  'php83Extensions.xml',
  'php83Extensions.zip',
  'php83Extensions.curl',
  'php83Extensions.intl',
  'composer'
]

[start]
cmd = "vendor/bin/heroku-php-apache2"
