version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-management-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      # Local development defaults (overridden by .env file)
      - APP_ENV=development
      - APP_DEBUG=true
      # Database configuration (can be overridden by .env)
      - MYSQL_URL=${MYSQL_URL:-mysql://root:password@db:3306/school}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-school}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - student-network

  db:
    image: mysql:8.0
    container_name: student-management-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-school}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT:-4306}:3306"
    networks:
      - student-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: student-management-pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME:-root}
      PMA_PASSWORD: ${DB_PASSWORD:-password}
      UPLOAD_LIMIT: 128M
    depends_on:
      - db
    ports:
      - "${PMA_PORT:-8081}:80"
    networks:
      - student-network

networks:
  student-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
