version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=schoolproject
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    restart: unless-stopped
    networks:
      - student-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: schoolproject
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "4306:3306"
    networks:
      - student-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - student-network

networks:
  student-network:
    driver: bridge

volumes:
  mysql_data:
