[build]
builder = "dockerfile"

[deploy]
startCommand = "apache2-foreground"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[build.dockerfile]
path = "Dockerfile"

[build.ignore]
files = [
  ".git",
  ".github",
  ".vscode",
  ".idea",
  "node_modules",
  "vendor",
  "*.md",
  "*.log",
  "*.sqlite",
  ".env*",
  "docker-compose*"
]

[build.environment]
APP_ENV = "production"
APP_DEBUG = "false"
